version: '3.8'

# Gerando image/container php:7.4
services:
  php: 
    build: 
      context: .
    image: qrcode-php
    container_name: qrcode-generate
    ports:
      - '9000:9000'
    volumes:
      - '.:/var/www/html'
    command: php -S 0.0.0.0:9000 -t public/

    